/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { draco } from 'drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/cube.glb', draco('/draco-gltf/'))
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[7.36, 4.96, 6.93]} rotation={[1.24, 0.33, -0.76]}>
        <primitive object={nodes.Camera_Orientation} />
      </group>
      <mesh material={materials.Material} geometry={nodes.Cube.geometry} />
    </group>
  )
}
